name: Build C3 Super Mini (SH1106)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.1
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/build.py esp32-c3-super-mini --name esp32-c3-super-mini-sh1106

      - name: Upload firmware
        uses: actions/upload-artifact@v7
        with:
          name: xiaozhi-esp32-c3-super-mini-sh1106
          path: build/merged-binary.bin
          if-no-files-found: error
